### PR TITLE
systemd support

### PR DESCRIPTION
**Pull request by ramereth**
This provides support for CentOS 7+

### CODE REVIEW

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs please review

**Comment by armiller** [comment]
Here is the syslog output when I run kitchen.

```
Jun  2 15:56:40 localhost yum[12738]: Installed: ucarp-1.5.2-11.el7.x86_64
Jun  2 15:56:41 localhost systemd: Starting system-ucarp.slice.
Jun  2 15:56:41 localhost systemd: Created slice system-ucarp.slice.
Jun  2 15:56:41 localhost systemd: Starting Common address redundancy protocol daemon on vip/001...
Jun  2 15:56:41 localhost ucarp: /usr/libexec/ucarp/ucarp: line 10: [: =: unary operator expected
Jun  2 15:56:41 localhost ucarp: all ucarp configurations were applied successfully
Jun  2 15:56:41 localhost ucarp: Starting common address redundancy protocol daemon: [  OK  ]
Jun  2 15:56:41 localhost systemd: Started Common address redundancy protocol daemon on vip/001.
Jun  2 15:56:41 localhost ucarp[12778]: [ERROR] Unable to get hardware info about an interface: No such device
Jun  2 15:56:41 localhost ucarp[12778]: [ERROR] Unable to find MAC address of [eth0]
Jun  2 15:56:41 localhost systemd: ucarp@vip-001.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun  2 15:56:41 localhost systemd: Unit ucarp@vip-001.service entered failed state.
Jun  2 15:56:42 localhost systemd: Starting Common address redundancy protocol daemon on vip/001...
Jun  2 15:56:42 localhost ucarp: /usr/libexec/ucarp/ucarp: line 10: [: =: unary operator expected
Jun  2 15:56:42 localhost ucarp: all ucarp configurations were applied successfully
Jun  2 15:56:42 localhost ucarp: Starting common address redundancy protocol daemon: [  OK  ]
Jun  2 15:56:42 localhost systemd: Started Common address redundancy protocol daemon on vip/001.
Jun  2 15:56:42 localhost ucarp[12814]: [ERROR] Unable to get hardware info about an interface: No such device
Jun  2 15:56:42 localhost ucarp[12814]: [ERROR] Unable to find MAC address of [eth0]
Jun  2 15:56:42 localhost systemd: ucarp@vip-001.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun  2 15:56:42 localhost systemd: Unit ucarp@vip-001.service entered failed state.
```

I thought we needed that template provided from [here](http://blog.oddbit.com/2013/02/21/ucarp-unit-for-systemd/). Also we should put the symlink in the `multi-user.target.wants` directory since the service depends on it.

**Comment by armiller** [comment]
I manually picked the correct interface name and it worked great. :+1:

**Comment by ramereth** [comment]
@armiller ya, the bento vagrant box uses the `em*` interface naming scheme, while our openstack images uses the `eth*` naming scheme. I'm not sure how we can fix this without having a different databag for CentOS 7 vagrant. There is another method we could use and rename the interface using a test cookbook.

**Comment by jordane** [comment]
+1

**Pull request merged**
